/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Kinde.ManagementApi.Client.FileParameter;
using OpenAPIDateConverter = Kinde.ManagementApi.Client.OpenAPIDateConverter;

namespace Kinde.ManagementApi.Model
{
    /// <summary>
    /// UpdateRolesRequest
    /// </summary>
    [DataContract(Name = "UpdateRoles_request")]
    public partial class UpdateRolesRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRolesRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateRolesRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateRolesRequest" /> class.
        /// </summary>
        /// <param name="name">The role&#39;s name. (required).</param>
        /// <param name="description">The role&#39;s description..</param>
        /// <param name="key">The role identifier to use in code. (required).</param>
        /// <param name="isDefaultRole">Set role as default for new users..</param>
        public UpdateRolesRequest(string name = default(string), string description = default(string), string key = default(string), bool isDefaultRole = default(bool))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for UpdateRolesRequest and cannot be null");
            }
            this.Name = name;
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for UpdateRolesRequest and cannot be null");
            }
            this.Key = key;
            this.Description = description;
            this.IsDefaultRole = isDefaultRole;
        }

        /// <summary>
        /// The role&#39;s name.
        /// </summary>
        /// <value>The role&#39;s name.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The role&#39;s description.
        /// </summary>
        /// <value>The role&#39;s description.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The role identifier to use in code.
        /// </summary>
        /// <value>The role identifier to use in code.</value>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Set role as default for new users.
        /// </summary>
        /// <value>Set role as default for new users.</value>
        [DataMember(Name = "is_default_role", EmitDefaultValue = true)]
        public bool IsDefaultRole { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateRolesRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  IsDefaultRole: ").Append(IsDefaultRole).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
