/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Kinde.ManagementApi.Client.FileParameter;
using OpenAPIDateConverter = Kinde.ManagementApi.Client.OpenAPIDateConverter;

namespace Kinde.ManagementApi.Model
{
    /// <summary>
    /// UpdateOrganizationUsersResponse
    /// </summary>
    [DataContract(Name = "update_organization_users_response")]
    public partial class UpdateOrganizationUsersResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOrganizationUsersResponse" /> class.
        /// </summary>
        /// <param name="message">message.</param>
        /// <param name="usersAdded">usersAdded.</param>
        /// <param name="usersUpdated">usersUpdated.</param>
        /// <param name="usersRemoved">usersRemoved.</param>
        public UpdateOrganizationUsersResponse(string message = default(string), List<string> usersAdded = default(List<string>), List<string> usersUpdated = default(List<string>), List<string> usersRemoved = default(List<string>))
        {
            this.Message = message;
            this.UsersAdded = usersAdded;
            this.UsersUpdated = usersUpdated;
            this.UsersRemoved = usersRemoved;
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets UsersAdded
        /// </summary>
        [DataMember(Name = "users_added", EmitDefaultValue = false)]
        public List<string> UsersAdded { get; set; }

        /// <summary>
        /// Gets or Sets UsersUpdated
        /// </summary>
        [DataMember(Name = "users_updated", EmitDefaultValue = false)]
        public List<string> UsersUpdated { get; set; }

        /// <summary>
        /// Gets or Sets UsersRemoved
        /// </summary>
        [DataMember(Name = "users_removed", EmitDefaultValue = false)]
        public List<string> UsersRemoved { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateOrganizationUsersResponse {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  UsersAdded: ").Append(UsersAdded).Append("\n");
            sb.Append("  UsersUpdated: ").Append(UsersUpdated).Append("\n");
            sb.Append("  UsersRemoved: ").Append(UsersRemoved).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
