/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kinde.ManagementApi.Model;
using Kinde.ManagementApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kinde.ManagementApi.Test.Model
{
    /// <summary>
    ///  Class for testing Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Api
        //private Api instance;

        public ApiTests()
        {
            // TODO uncomment below to create an instance of Api
            //instance = new Api();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Api
        /// </summary>
        [Fact]
        public void ApiInstanceTest()
        {
            // TODO uncomment below to test "IsType" Api
            //Assert.IsType<Api>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Audience'
        /// </summary>
        [Fact]
        public void AudienceTest()
        {
            // TODO unit test for the property 'Audience'
        }

        /// <summary>
        /// Test the property 'Applications'
        /// </summary>
        [Fact]
        public void ApplicationsTest()
        {
            // TODO unit test for the property 'Applications'
        }
    }
}
