/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Kinde.ManagementApi.Client.FileParameter;
using OpenAPIDateConverter = Kinde.ManagementApi.Client.OpenAPIDateConverter;

namespace Kinde.ManagementApi.Model
{
    /// <summary>
    /// ConnectedAppsAuthUrl
    /// </summary>
    [DataContract(Name = "connected_apps_auth_url")]
    public partial class ConnectedAppsAuthUrl : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectedAppsAuthUrl" /> class.
        /// </summary>
        /// <param name="url">A URL that is used to authenticate an end-user against a connected app..</param>
        /// <param name="sessionId">A unique identifier for the login session..</param>
        public ConnectedAppsAuthUrl(string url = default(string), string sessionId = default(string))
        {
            this.Url = url;
            this.SessionId = sessionId;
        }

        /// <summary>
        /// A URL that is used to authenticate an end-user against a connected app.
        /// </summary>
        /// <value>A URL that is used to authenticate an end-user against a connected app.</value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// A unique identifier for the login session.
        /// </summary>
        /// <value>A unique identifier for the login session.</value>
        [DataMember(Name = "session_id", EmitDefaultValue = false)]
        public string SessionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConnectedAppsAuthUrl {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
