/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Kinde.ManagementApi.Client.FileParameter;
using OpenAPIDateConverter = Kinde.ManagementApi.Client.OpenAPIDateConverter;

namespace Kinde.ManagementApi.Model
{
    /// <summary>
    /// UpdateAPIApplicationsRequest
    /// </summary>
    [DataContract(Name = "updateAPIApplications_request")]
    public partial class UpdateAPIApplicationsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateAPIApplicationsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateAPIApplicationsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateAPIApplicationsRequest" /> class.
        /// </summary>
        /// <param name="applications">applications (required).</param>
        public UpdateAPIApplicationsRequest(List<UpdateAPIApplicationsRequestApplicationsInner> applications = default(List<UpdateAPIApplicationsRequestApplicationsInner>))
        {
            // to ensure "applications" is required (not null)
            if (applications == null)
            {
                throw new ArgumentNullException("applications is a required property for UpdateAPIApplicationsRequest and cannot be null");
            }
            this.Applications = applications;
        }

        /// <summary>
        /// Gets or Sets Applications
        /// </summary>
        [DataMember(Name = "applications", IsRequired = true, EmitDefaultValue = true)]
        public List<UpdateAPIApplicationsRequestApplicationsInner> Applications { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateAPIApplicationsRequest {\n");
            sb.Append("  Applications: ").Append(Applications).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
