/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Kinde.ManagementApi.Client.FileParameter;
using OpenAPIDateConverter = Kinde.ManagementApi.Client.OpenAPIDateConverter;

namespace Kinde.ManagementApi.Model
{
    /// <summary>
    /// UserProfileV2
    /// </summary>
    [DataContract(Name = "user_profile_v2")]
    public partial class UserProfileV2 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserProfileV2" /> class.
        /// </summary>
        /// <param name="id">Unique id of the user in Kinde (deprecated)..</param>
        /// <param name="sub">Unique id of the user in Kinde..</param>
        /// <param name="providedId">Value of the user&#39;s id in a third-party system when the user is imported into Kinde..</param>
        /// <param name="name">Users&#39;s first and last name separated by a space..</param>
        /// <param name="givenName">User&#39;s first name..</param>
        /// <param name="familyName">User&#39;s last name..</param>
        /// <param name="updatedAt">Date the user was last updated at (In Unix time)..</param>
        /// <param name="email">User&#39;s email address if available..</param>
        /// <param name="picture">URL that point&#39;s to the user&#39;s picture or avatar.</param>
        public UserProfileV2(string id = default(string), string sub = default(string), string providedId = default(string), string name = default(string), string givenName = default(string), string familyName = default(string), int updatedAt = default(int), string email = default(string), string picture = default(string))
        {
            this.Id = id;
            this.Sub = sub;
            this.ProvidedId = providedId;
            this.Name = name;
            this.GivenName = givenName;
            this.FamilyName = familyName;
            this.UpdatedAt = updatedAt;
            this.Email = email;
            this.Picture = picture;
        }

        /// <summary>
        /// Unique id of the user in Kinde (deprecated).
        /// </summary>
        /// <value>Unique id of the user in Kinde (deprecated).</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Unique id of the user in Kinde.
        /// </summary>
        /// <value>Unique id of the user in Kinde.</value>
        [DataMember(Name = "sub", EmitDefaultValue = false)]
        public string Sub { get; set; }

        /// <summary>
        /// Value of the user&#39;s id in a third-party system when the user is imported into Kinde.
        /// </summary>
        /// <value>Value of the user&#39;s id in a third-party system when the user is imported into Kinde.</value>
        [DataMember(Name = "provided_id", EmitDefaultValue = true)]
        public string ProvidedId { get; set; }

        /// <summary>
        /// Users&#39;s first and last name separated by a space.
        /// </summary>
        /// <value>Users&#39;s first and last name separated by a space.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// User&#39;s first name.
        /// </summary>
        /// <value>User&#39;s first name.</value>
        [DataMember(Name = "given_name", EmitDefaultValue = false)]
        public string GivenName { get; set; }

        /// <summary>
        /// User&#39;s last name.
        /// </summary>
        /// <value>User&#39;s last name.</value>
        [DataMember(Name = "family_name", EmitDefaultValue = false)]
        public string FamilyName { get; set; }

        /// <summary>
        /// Date the user was last updated at (In Unix time).
        /// </summary>
        /// <value>Date the user was last updated at (In Unix time).</value>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public int UpdatedAt { get; set; }

        /// <summary>
        /// User&#39;s email address if available.
        /// </summary>
        /// <value>User&#39;s email address if available.</value>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// URL that point&#39;s to the user&#39;s picture or avatar
        /// </summary>
        /// <value>URL that point&#39;s to the user&#39;s picture or avatar</value>
        [DataMember(Name = "picture", EmitDefaultValue = false)]
        public string Picture { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserProfileV2 {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Sub: ").Append(Sub).Append("\n");
            sb.Append("  ProvidedId: ").Append(ProvidedId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  GivenName: ").Append(GivenName).Append("\n");
            sb.Append("  FamilyName: ").Append(FamilyName).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Picture: ").Append(Picture).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
