/*
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Kinde.ManagementApi.Client;
using Kinde.ManagementApi.Model;

namespace Kinde.ManagementApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPropertiesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Property
        /// </summary>
        /// <remarks>
        /// Create property.
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPropertyRequest">Property details.</param>
        /// <returns>CreatePropertyResponse</returns>
        CreatePropertyResponse CreateProperty(CreatePropertyRequest createPropertyRequest);

        /// <summary>
        /// Create Property
        /// </summary>
        /// <remarks>
        /// Create property.
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPropertyRequest">Property details.</param>
        /// <returns>ApiResponse of CreatePropertyResponse</returns>
        ApiResponse<CreatePropertyResponse> CreatePropertyWithHttpInfo(CreatePropertyRequest createPropertyRequest);
        /// <summary>
        /// List properties
        /// </summary>
        /// <remarks>
        /// Returns a list of properties 
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageSize">Number of results per page. Defaults to 10 if parameter not sent. (optional)</param>
        /// <param name="startingAfter">The ID of the property to start after. (optional)</param>
        /// <param name="endingBefore">The ID of the property to end before. (optional)</param>
        /// <param name="context">Filter results by User or Organization context (optional)</param>
        /// <returns>GetPropertiesResponse</returns>
        GetPropertiesResponse GetProperties(int? pageSize = default(int?), string? startingAfter = default(string?), string? endingBefore = default(string?), string? context = default(string?));

        /// <summary>
        /// List properties
        /// </summary>
        /// <remarks>
        /// Returns a list of properties 
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageSize">Number of results per page. Defaults to 10 if parameter not sent. (optional)</param>
        /// <param name="startingAfter">The ID of the property to start after. (optional)</param>
        /// <param name="endingBefore">The ID of the property to end before. (optional)</param>
        /// <param name="context">Filter results by User or Organization context (optional)</param>
        /// <returns>ApiResponse of GetPropertiesResponse</returns>
        ApiResponse<GetPropertiesResponse> GetPropertiesWithHttpInfo(int? pageSize = default(int?), string? startingAfter = default(string?), string? endingBefore = default(string?), string? context = default(string?));
        /// <summary>
        /// Update Property
        /// </summary>
        /// <remarks>
        /// Update property.
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId">The unique identifier for the property.</param>
        /// <param name="updatePropertyRequest">The fields of the property to update.</param>
        /// <returns>SuccessResponse</returns>
        SuccessResponse UpdateProperty(string propertyId, UpdatePropertyRequest updatePropertyRequest);

        /// <summary>
        /// Update Property
        /// </summary>
        /// <remarks>
        /// Update property.
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId">The unique identifier for the property.</param>
        /// <param name="updatePropertyRequest">The fields of the property to update.</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        ApiResponse<SuccessResponse> UpdatePropertyWithHttpInfo(string propertyId, UpdatePropertyRequest updatePropertyRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPropertiesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Property
        /// </summary>
        /// <remarks>
        /// Create property.
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPropertyRequest">Property details.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreatePropertyResponse</returns>
        System.Threading.Tasks.Task<CreatePropertyResponse> CreatePropertyAsync(CreatePropertyRequest createPropertyRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create Property
        /// </summary>
        /// <remarks>
        /// Create property.
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPropertyRequest">Property details.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreatePropertyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreatePropertyResponse>> CreatePropertyWithHttpInfoAsync(CreatePropertyRequest createPropertyRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List properties
        /// </summary>
        /// <remarks>
        /// Returns a list of properties 
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageSize">Number of results per page. Defaults to 10 if parameter not sent. (optional)</param>
        /// <param name="startingAfter">The ID of the property to start after. (optional)</param>
        /// <param name="endingBefore">The ID of the property to end before. (optional)</param>
        /// <param name="context">Filter results by User or Organization context (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPropertiesResponse</returns>
        System.Threading.Tasks.Task<GetPropertiesResponse> GetPropertiesAsync(int? pageSize = default(int?), string? startingAfter = default(string?), string? endingBefore = default(string?), string? context = default(string?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List properties
        /// </summary>
        /// <remarks>
        /// Returns a list of properties 
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageSize">Number of results per page. Defaults to 10 if parameter not sent. (optional)</param>
        /// <param name="startingAfter">The ID of the property to start after. (optional)</param>
        /// <param name="endingBefore">The ID of the property to end before. (optional)</param>
        /// <param name="context">Filter results by User or Organization context (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPropertiesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetPropertiesResponse>> GetPropertiesWithHttpInfoAsync(int? pageSize = default(int?), string? startingAfter = default(string?), string? endingBefore = default(string?), string? context = default(string?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Property
        /// </summary>
        /// <remarks>
        /// Update property.
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId">The unique identifier for the property.</param>
        /// <param name="updatePropertyRequest">The fields of the property to update.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SuccessResponse</returns>
        System.Threading.Tasks.Task<SuccessResponse> UpdatePropertyAsync(string propertyId, UpdatePropertyRequest updatePropertyRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update Property
        /// </summary>
        /// <remarks>
        /// Update property.
        /// </remarks>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId">The unique identifier for the property.</param>
        /// <param name="updatePropertyRequest">The fields of the property to update.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SuccessResponse>> UpdatePropertyWithHttpInfoAsync(string propertyId, UpdatePropertyRequest updatePropertyRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPropertiesApi : IPropertiesApiSync, IPropertiesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PropertiesApi : IDisposable, IPropertiesApi
    {
        private Kinde.ManagementApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PropertiesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PropertiesApi(string basePath)
        {
            this.Configuration = Kinde.ManagementApi.Client.Configuration.MergeConfigurations(
                Kinde.ManagementApi.Client.GlobalConfiguration.Instance,
                new Kinde.ManagementApi.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Kinde.ManagementApi.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Kinde.ManagementApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PropertiesApi(Kinde.ManagementApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Kinde.ManagementApi.Client.Configuration.MergeConfigurations(
                Kinde.ManagementApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Kinde.ManagementApi.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Kinde.ManagementApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PropertiesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PropertiesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Kinde.ManagementApi.Client.Configuration.MergeConfigurations(
                Kinde.ManagementApi.Client.GlobalConfiguration.Instance,
                new Kinde.ManagementApi.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Kinde.ManagementApi.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Kinde.ManagementApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PropertiesApi(HttpClient client, Kinde.ManagementApi.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Kinde.ManagementApi.Client.Configuration.MergeConfigurations(
                Kinde.ManagementApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Kinde.ManagementApi.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Kinde.ManagementApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PropertiesApi(Kinde.ManagementApi.Client.ISynchronousClient client, Kinde.ManagementApi.Client.IAsynchronousClient asyncClient, Kinde.ManagementApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Kinde.ManagementApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Kinde.ManagementApi.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Kinde.ManagementApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Kinde.ManagementApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Kinde.ManagementApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Kinde.ManagementApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Property Create property.
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPropertyRequest">Property details.</param>
        /// <returns>CreatePropertyResponse</returns>
        public CreatePropertyResponse CreateProperty(CreatePropertyRequest createPropertyRequest)
        {
            Kinde.ManagementApi.Client.ApiResponse<CreatePropertyResponse> localVarResponse = CreatePropertyWithHttpInfo(createPropertyRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Property Create property.
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPropertyRequest">Property details.</param>
        /// <returns>ApiResponse of CreatePropertyResponse</returns>
        public Kinde.ManagementApi.Client.ApiResponse<CreatePropertyResponse> CreatePropertyWithHttpInfo(CreatePropertyRequest createPropertyRequest)
        {
            // verify the required parameter 'createPropertyRequest' is set
            if (createPropertyRequest == null)
                throw new Kinde.ManagementApi.Client.ApiException(400, "Missing required parameter 'createPropertyRequest' when calling PropertiesApi->CreateProperty");

            Kinde.ManagementApi.Client.RequestOptions localVarRequestOptions = new Kinde.ManagementApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/json; charset=utf-8"
            };

            var localVarContentType = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createPropertyRequest;

            // authentication (kindeBearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreatePropertyResponse>("/api/v1/properties", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateProperty", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Property Create property.
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPropertyRequest">Property details.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreatePropertyResponse</returns>
        public async System.Threading.Tasks.Task<CreatePropertyResponse> CreatePropertyAsync(CreatePropertyRequest createPropertyRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Kinde.ManagementApi.Client.ApiResponse<CreatePropertyResponse> localVarResponse = await CreatePropertyWithHttpInfoAsync(createPropertyRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Property Create property.
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPropertyRequest">Property details.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreatePropertyResponse)</returns>
        public async System.Threading.Tasks.Task<Kinde.ManagementApi.Client.ApiResponse<CreatePropertyResponse>> CreatePropertyWithHttpInfoAsync(CreatePropertyRequest createPropertyRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'createPropertyRequest' is set
            if (createPropertyRequest == null)
                throw new Kinde.ManagementApi.Client.ApiException(400, "Missing required parameter 'createPropertyRequest' when calling PropertiesApi->CreateProperty");


            Kinde.ManagementApi.Client.RequestOptions localVarRequestOptions = new Kinde.ManagementApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/json; charset=utf-8"
            };


            var localVarContentType = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createPropertyRequest;

            // authentication (kindeBearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreatePropertyResponse>("/api/v1/properties", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateProperty", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List properties Returns a list of properties 
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageSize">Number of results per page. Defaults to 10 if parameter not sent. (optional)</param>
        /// <param name="startingAfter">The ID of the property to start after. (optional)</param>
        /// <param name="endingBefore">The ID of the property to end before. (optional)</param>
        /// <param name="context">Filter results by User or Organization context (optional)</param>
        /// <returns>GetPropertiesResponse</returns>
        public GetPropertiesResponse GetProperties(int? pageSize = default(int?), string? startingAfter = default(string?), string? endingBefore = default(string?), string? context = default(string?))
        {
            Kinde.ManagementApi.Client.ApiResponse<GetPropertiesResponse> localVarResponse = GetPropertiesWithHttpInfo(pageSize, startingAfter, endingBefore, context);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List properties Returns a list of properties 
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageSize">Number of results per page. Defaults to 10 if parameter not sent. (optional)</param>
        /// <param name="startingAfter">The ID of the property to start after. (optional)</param>
        /// <param name="endingBefore">The ID of the property to end before. (optional)</param>
        /// <param name="context">Filter results by User or Organization context (optional)</param>
        /// <returns>ApiResponse of GetPropertiesResponse</returns>
        public Kinde.ManagementApi.Client.ApiResponse<GetPropertiesResponse> GetPropertiesWithHttpInfo(int? pageSize = default(int?), string? startingAfter = default(string?), string? endingBefore = default(string?), string? context = default(string?))
        {
            Kinde.ManagementApi.Client.RequestOptions localVarRequestOptions = new Kinde.ManagementApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json; charset=utf-8",
                "application/json"
            };

            var localVarContentType = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kinde.ManagementApi.Client.ClientUtils.ParameterToMultiMap("", "page_size", pageSize));
            }
            if (startingAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kinde.ManagementApi.Client.ClientUtils.ParameterToMultiMap("", "starting_after", startingAfter));
            }
            if (endingBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kinde.ManagementApi.Client.ClientUtils.ParameterToMultiMap("", "ending_before", endingBefore));
            }
            if (context != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kinde.ManagementApi.Client.ClientUtils.ParameterToMultiMap("", "context", context));
            }

            // authentication (kindeBearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetPropertiesResponse>("/api/v1/properties", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProperties", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List properties Returns a list of properties 
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageSize">Number of results per page. Defaults to 10 if parameter not sent. (optional)</param>
        /// <param name="startingAfter">The ID of the property to start after. (optional)</param>
        /// <param name="endingBefore">The ID of the property to end before. (optional)</param>
        /// <param name="context">Filter results by User or Organization context (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPropertiesResponse</returns>
        public async System.Threading.Tasks.Task<GetPropertiesResponse> GetPropertiesAsync(int? pageSize = default(int?), string? startingAfter = default(string?), string? endingBefore = default(string?), string? context = default(string?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Kinde.ManagementApi.Client.ApiResponse<GetPropertiesResponse> localVarResponse = await GetPropertiesWithHttpInfoAsync(pageSize, startingAfter, endingBefore, context, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List properties Returns a list of properties 
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageSize">Number of results per page. Defaults to 10 if parameter not sent. (optional)</param>
        /// <param name="startingAfter">The ID of the property to start after. (optional)</param>
        /// <param name="endingBefore">The ID of the property to end before. (optional)</param>
        /// <param name="context">Filter results by User or Organization context (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPropertiesResponse)</returns>
        public async System.Threading.Tasks.Task<Kinde.ManagementApi.Client.ApiResponse<GetPropertiesResponse>> GetPropertiesWithHttpInfoAsync(int? pageSize = default(int?), string? startingAfter = default(string?), string? endingBefore = default(string?), string? context = default(string?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Kinde.ManagementApi.Client.RequestOptions localVarRequestOptions = new Kinde.ManagementApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json; charset=utf-8",
                "application/json"
            };


            var localVarContentType = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kinde.ManagementApi.Client.ClientUtils.ParameterToMultiMap("", "page_size", pageSize));
            }
            if (startingAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kinde.ManagementApi.Client.ClientUtils.ParameterToMultiMap("", "starting_after", startingAfter));
            }
            if (endingBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kinde.ManagementApi.Client.ClientUtils.ParameterToMultiMap("", "ending_before", endingBefore));
            }
            if (context != null)
            {
                localVarRequestOptions.QueryParameters.Add(Kinde.ManagementApi.Client.ClientUtils.ParameterToMultiMap("", "context", context));
            }

            // authentication (kindeBearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetPropertiesResponse>("/api/v1/properties", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProperties", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Property Update property.
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId">The unique identifier for the property.</param>
        /// <param name="updatePropertyRequest">The fields of the property to update.</param>
        /// <returns>SuccessResponse</returns>
        public SuccessResponse UpdateProperty(string propertyId, UpdatePropertyRequest updatePropertyRequest)
        {
            Kinde.ManagementApi.Client.ApiResponse<SuccessResponse> localVarResponse = UpdatePropertyWithHttpInfo(propertyId, updatePropertyRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Property Update property.
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId">The unique identifier for the property.</param>
        /// <param name="updatePropertyRequest">The fields of the property to update.</param>
        /// <returns>ApiResponse of SuccessResponse</returns>
        public Kinde.ManagementApi.Client.ApiResponse<SuccessResponse> UpdatePropertyWithHttpInfo(string propertyId, UpdatePropertyRequest updatePropertyRequest)
        {
            // verify the required parameter 'propertyId' is set
            if (propertyId == null)
                throw new Kinde.ManagementApi.Client.ApiException(400, "Missing required parameter 'propertyId' when calling PropertiesApi->UpdateProperty");

            // verify the required parameter 'updatePropertyRequest' is set
            if (updatePropertyRequest == null)
                throw new Kinde.ManagementApi.Client.ApiException(400, "Missing required parameter 'updatePropertyRequest' when calling PropertiesApi->UpdateProperty");

            Kinde.ManagementApi.Client.RequestOptions localVarRequestOptions = new Kinde.ManagementApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/json; charset=utf-8"
            };

            var localVarContentType = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("property_id", Kinde.ManagementApi.Client.ClientUtils.ParameterToString(propertyId)); // path parameter
            localVarRequestOptions.Data = updatePropertyRequest;

            // authentication (kindeBearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<SuccessResponse>("/api/v1/properties/{property_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateProperty", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Property Update property.
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId">The unique identifier for the property.</param>
        /// <param name="updatePropertyRequest">The fields of the property to update.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SuccessResponse</returns>
        public async System.Threading.Tasks.Task<SuccessResponse> UpdatePropertyAsync(string propertyId, UpdatePropertyRequest updatePropertyRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Kinde.ManagementApi.Client.ApiResponse<SuccessResponse> localVarResponse = await UpdatePropertyWithHttpInfoAsync(propertyId, updatePropertyRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Property Update property.
        /// </summary>
        /// <exception cref="Kinde.ManagementApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyId">The unique identifier for the property.</param>
        /// <param name="updatePropertyRequest">The fields of the property to update.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SuccessResponse)</returns>
        public async System.Threading.Tasks.Task<Kinde.ManagementApi.Client.ApiResponse<SuccessResponse>> UpdatePropertyWithHttpInfoAsync(string propertyId, UpdatePropertyRequest updatePropertyRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'propertyId' is set
            if (propertyId == null)
                throw new Kinde.ManagementApi.Client.ApiException(400, "Missing required parameter 'propertyId' when calling PropertiesApi->UpdateProperty");

            // verify the required parameter 'updatePropertyRequest' is set
            if (updatePropertyRequest == null)
                throw new Kinde.ManagementApi.Client.ApiException(400, "Missing required parameter 'updatePropertyRequest' when calling PropertiesApi->UpdateProperty");


            Kinde.ManagementApi.Client.RequestOptions localVarRequestOptions = new Kinde.ManagementApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/json; charset=utf-8"
            };


            var localVarContentType = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Kinde.ManagementApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("property_id", Kinde.ManagementApi.Client.ClientUtils.ParameterToString(propertyId)); // path parameter
            localVarRequestOptions.Data = updatePropertyRequest;

            // authentication (kindeBearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<SuccessResponse>("/api/v1/properties/{property_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateProperty", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
